ImmedisTask/ViewModels/Comment/CommentViewModel.cs
namespace ImmedisTask.ViewModels.Comment
{
    public class CommentViewModel
    {
        public int Id { get; set; }

        public string Author { get; set; }

        public string CommentContent { get; set; }

        public string CreatedDateTime { get; set; }
    }
}

ImmedisTask/ViewModels/Comment/IndexViewModel.cs
using System.Collections.Generic;

namespace ImmedisTask.ViewModels.Comment
{
    public class IndexViewModel
    {
        public int EmployeeId { get; set; }

        public IEnumerable<CommentViewModel> Comments { get; set; }
    }
}

ImmedisTask/Controllers/CommentController.cs
using ImmedisTask.Data.Interfaces;
using ImmedisTask.Data.Models;
using ImmedisTask.InputModels;
using ImmedisTask.ViewModels.Comment;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ImmedisTask.Controllers
{
    public class CommentController : Controller
    {
        private ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        public IActionResult Index(int employeeId)
        {
            var comments = _commentService.GetByEmployeeId(employeeId);
            var models = comments.Select(x => new CommentViewModel
            {
                Id = x.Id,
                Author = x.Author,
                CommentContent = x.CommentContent.Length > 50
                ? $"{x.CommentContent.Substring(0, 50)}..."
                : x.CommentContent,
                CreatedDateTime = x.CreatedDateTime.ToString("dd.MM.yyyy")
            });

            var indexViewModel = new IndexViewModel 
            { 
                EmployeeId = employeeId,
                Comments = models
            };

            return View(indexViewModel);
        }

        public async Task<IActionResult> Edit(int? commentId, int employeeId)
        {
            var comment = await _commentService.GetByIdAsync(commentId);
            if (comment == null)
            {
                var inputModel = new CommentInputModel
                {
                    EmployeeId = employeeId
                };

                return View(inputModel);
            }
            else
            {
                var inputModel = new CommentInputModel
                {
                    Id = comment.Id,
                    EmployeeId = employeeId,
                    Author = comment.Author,
                    CommentContent = comment.CommentContent
                };

                return View(inputModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CommentInputModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var comment = await _commentService.GetByIdAsync(model.Id);
            if (comment == null)
            {
                comment = new Comment
                {
                    Author = model.Author,
                    CommentContent = model.CommentContent,
                    EmployeeId = model.EmployeeId,
                    CreatedDateTime = DateTime.Now,
                    IsActive = true
                };
            }
            else
            {
                comment.Author = model.Author;
                comment.CommentContent = model.CommentContent;
                comment.EmployeeId = model.EmployeeId;
                comment.LastUpdatedDateTime = DateTime.Now;
            }

            await _commentService.SaveChangesAsync(comment);
            return Redirect($"/Comment/Index?employeeId={model.EmployeeId}");
        }
    }
}

ImmedisTask/Views/Comment/Edit.cshtml
@model ImmedisTask.InputModels.CommentInputModel

@{
    ViewData["Title"] = "Comment editor";
}

<form method="post">
    <input type="hidden" asp-for="Id" />

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CommentContent"></label>
        <textarea asp-for="CommentContent" class="form-control"></textarea>
        <span asp-validation-for="CommentContent" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary btn-user btn-block">
        Save
    </button>
</form>

ImmedisTask/Views/Comment/Index.cshtml
@model ImmedisTask.ViewModels.Comment.IndexViewModel

@{
    ViewData["Title"] = "Comments";
}

<a asp-area="" asp-controller="Home" asp-action="Index">Go back to employees</a>
<br />
<a asp-area="" asp-controller="Comment" asp-action="Edit" asp-route-employeeId="@Model.EmployeeId">Create new comment</a>
<br />
<br />

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Author</th>
            <th scope="col">Content</th>
            <th scope="col">Created on</th>
            <th scope="col">Modify</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var comment in Model.Comments)
        {
            <tr>
                <td>@comment.Author</td>
                <td>@comment.CommentContent</td>
                <td>@comment.CreatedDateTime</td>
                <td>
                    <a asp-area="" asp-controller="Comment" asp-action="Edit" asp-route-commentId="@comment.Id" asp-route-employeeId="@Model.EmployeeId">
                        Edit
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>